Assignment Expression Inside Tuple
warrenseine/prettier-plugin-csharp pull request #19
Opened 2019-08-14 02:26 UTC by CharlesTaylor7

Tuple literals allow any kind of expression in them, including assignment. I verified in Sharplab.io: https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEA3GUCWAZgJ5oAmIA1AD4ACATAIwCwAULQMwAEDXAwlwDebLqJ7daKLgFkAFAEohIsSuwBDKF2BcAvF3oBuZStHrNhCBF1dZHNDe1768+UdYqAvmw9A=

2019-08-14 06:27 UTC, johnnyreilly commented
Nice!

2019-08-18 12:04 UTC, warrenseine requested changes

2019-08-18 12:04 UTC, warrenseine commented on src/csharp/CSharpParser.g4
> +	: OPEN_PARENS tuple_element_initializer (',' tuple_element_initializer)+ CLOSE_PARENS
This change could be a separate commit because it's a bug fix (thanks!).

2019-08-18 12:04 UTC, warrenseine commented on test/AllInOne.cs
> +        var foo = (2, a=1);
I'd prefer you move this test case among the other tuple-related cases around line 345. No need for a separate class.

2019-08-18 12:16 UTC, warrenseine commented
This is scary as hell that this is allowed by the compiler. I would never accept any code that look like this in production.

Anyway, thanks for the contribution. It looks good to me, I just asked for minor changes.

2019-08-23 07:17 UTC, warrenseine approved these changes

2019-08-23 07:17 UTC, warrenseine commented on test/AllInOne.cs
> +#line hidden
Technically, the absence of final newline in the original file ensured that a newline was inserted by Prettier. However, I realize that this is pointless to test that as this is dealt with and tested by Prettier. No need to test it again here.

2019-08-23 07:17 UTC, merged

2019-08-23 07:18 UTC, warrenseine commented
Thanks!