Constant patterns with is operator
warrenseine/prettier-plugin-csharp pull request #22
Opened 2019-08-18 03:25 UTC by CharlesTaylor7

Support for [constant patterns w/ is operator](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/is#constant-pattern).

2019-08-18 06:18 UTC, johnnyreilly commented
So cool to see all the activity here!

2019-08-18 12:37 UTC, warrenseine requested changes

2019-08-18 12:37 UTC, warrenseine commented on src/csharp/CSharpParser.g4
> +  | SWITCH OPEN_PARENS expression CLOSE_PARENS OPEN_BRACE switch_section* CLOSE_BRACE           #switchStatement
I'm not sure if indentation is incorrect or just GitHub reviews that make it look incorrect.

2019-08-18 12:37 UTC, warrenseine commented on test/CSharp7Features.cs
> +      if (3 is int foo) {}
Please keep everything in the same (long) `AllInOne.cs` file. No need for a specific C# 7 namespace / file.

2019-08-18 12:38 UTC, warrenseine commented
Thanks a lot! As mentioned in another PR, let's merge the PR that removes the generated files first.

2019-08-25 07:29 UTC, warrenseine commented
Argh. I tried fixing the tabs conflicts from the UI and GitHub produced a merge commit... I'll rewrite and force-push, sorry for that.

2019-08-25 08:13 UTC, warrenseine commented
Hum, GitHub doesn't understand that I updated your commit to resolved conflicts and pushed it to master. I probably skipped a step somewhere. Anyway, let's closed this PR now!

2019-08-25 08:13 UTC, closed without merging